# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 13.3.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
          environment:
            SCAN_DEVICE: iPhone 11
            SCAN_SCHEME: MailBoxSample
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build-and-test
