on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    defaults:
      run:
        working-directory: MailBoxSample
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Check Environment
      run: |
          xcodebuild -version
          swift --version
    - name: Install Dependencies
      run: pod install
    - name: Build
      run: xcodebuild build -workspace MailBoxSample.xcworkspace -scheme MailBoxSample -destination 'platform=iOS Simulator,name=iPhone 11'
